version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - user-service

  user-service:
    build: ./backend/user-service
    ports:
      - "5001:5000"
    command: npm start
    volumes:
      - ./backend/user-service:/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=${MONGO_URL}
      - USER_SERVICE_PORT=5000

volumes:
  mongo-data:
