version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service

  user-service:
    build: ./backend/user-service
    ports:
      - "5000:5000"
    command: npm start
    volumes:
      - ./backend/user-service:/app
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/cineconnect

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
